// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    "介绍",
    {
      type: "category",
      label: "概述",
      items: [
        "概述/第一步",
        "概述/控制器",
        "概述/提供者",
        "概述/模块",
        "概述/中间件",
        "概述/异常过滤器",
        "概述/管道",
        "概述/守卫",
        "概述/拦截器",
        "概述/自定义装饰器",
      ],
    },
    {
      type: "category",
      label: "基础",
      items: [
        "基础/自定义提供者",
        "基础/异步提供者",
        "基础/动态模块",
        "基础/注入作用域",
        "基础/循环依赖",
        "基础/模块引用",
        "基础/延迟加载模块",
        "基础/执行上下文",
        "基础/生命周期事件",
        "基础/平台无关",
        "基础/测试",
      ],
    },
  ],
};

export default sidebars;
