// @ts-nocheck

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    "介绍",
    {
      type: "category",
      label: "概述",
      items: [
        "概述/第一步",
        "概述/控制器",
        "概述/提供者",
        "概述/模块",
        "概述/中间件",
        "概述/异常过滤器",
        "概述/管道",
        "概述/守卫",
        "概述/拦截器",
        "概述/自定义装饰器",
      ],
    },
    {
      type: "category",
      label: "基础",
      items: [
        "基础/自定义提供者",
        "基础/异步提供者",
        "基础/动态模块",
        "基础/注入作用域",
        "基础/循环依赖",
        "基础/模块引用",
        "基础/延迟加载模块",
        "基础/执行上下文",
        "基础/生命周期事件",
        "基础/平台无关",
        "基础/测试",
      ],
    },
    {
      type: "category",
      label: "技术",
      items: [
        "技术/配置",
        "技术/数据库",
        "技术/Mongo",
        "技术/验证",
        "技术/缓存",
        "技术/序列化",
        "技术/版本控制",
        "技术/任务调度",
        "技术/队列",
        "技术/日志",
        "技术/Cookies",
        "技术/事件",
        "技术/压缩",
        "技术/文件上传",
        "技术/流式处理文件",
        "技术/HTTP模块",
        "技术/Session",
        "技术/Model-View-Controller",
        "技术/Fastify",
        "技术/服务器推送",
      ],
    },
    {
      type: "category",
      label: "安全",
      items: [
        "安全/认证",
        "安全/授权",
        "安全/加密和哈希",
        "安全/Helmet",
        "安全/CORS",
        "安全/CSRF保护",
        "安全/速率限制",
      ],
    },
  ],
};

export default sidebars;
