/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  tutorialSidebar: [
    "介绍",
    {
      type: "category",
      label: "概述",
      items: [
        "概述/第一步",
        "概述/控制器",
        "概述/提供者",
        "概述/模块",
        "概述/中间件",
        "概述/异常过滤器",
        "概述/管道",
        "概述/守卫",
        "概述/拦截器",
        "概述/自定义装饰器",
      ],
    },
  ],
};

export default sidebars;
